#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataversePolicyEnforcement.Models
{
	
	
	/// <summary>
	/// Status of the Policy Condition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum dpe_policycondition_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Policy Condition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum dpe_policycondition_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dpe_policycondition")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class dpe_PolicyCondition : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dpe_policycondition entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string dpe_CompareAttributeLogicalName = "dpe_compareattributelogicalname";
			public const string dpe_CompareTo = "dpe_compareto";
			public const string dpe_comparetoName = "dpe_comparetoname";
			public const string dpe_Name = "dpe_name";
			public const string dpe_Operator = "dpe_operator";
			public const string dpe_operatorName = "dpe_operatorname";
			public const string dpe_PolicyConditionId = "dpe_policyconditionid";
			public const string Id = "dpe_policyconditionid";
			public const string dpe_PolicyRuleId = "dpe_policyruleid";
			public const string dpe_PolicyRuleIdName = "dpe_policyruleidname";
			public const string dpe_Sequence = "dpe_sequence";
			public const string dpe_ValueBoolean = "dpe_valueboolean";
			public const string dpe_valuebooleanName = "dpe_valuebooleanname";
			public const string dpe_ValueDateTime = "dpe_valuedatetime";
			public const string dpe_ValueDecimal = "dpe_valuedecimal";
			public const string dpe_ValueGuid = "dpe_valueguid";
			public const string dpe_ValueLookupId = "dpe_valuelookupid";
			public const string dpe_ValueLookupLogicalName = "dpe_valuelookuplogicalname";
			public const string dpe_ValueMoney = "dpe_valuemoney";
			public const string dpe_valuemoney_Base = "dpe_valuemoney_base";
			public const string dpe_ValueOptionSetValue = "dpe_valueoptionsetvalue";
			public const string dpe_ValueString = "dpe_valuestring";
			public const string dpe_ValueType = "dpe_valuetype";
			public const string dpe_valuetypeName = "dpe_valuetypename";
			public const string dpe_ValueWholeNumber = "dpe_valuewholenumber";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string dpe_policycondition_PolicyRuleId_dpe_policyrule = "dpe_policycondition_PolicyRuleId_dpe_policyrule";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public dpe_PolicyCondition() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "dpe_policycondition";
		
		public const string EntityLogicalCollectionName = "dpe_policyconditions";
		
		public const string EntitySetName = "dpe_policyconditions";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_compareattributelogicalname")]
		public string dpe_CompareAttributeLogicalName
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_compareattributelogicalname");
			}
			set
			{
				this.OnPropertyChanging("dpe_CompareAttributeLogicalName");
				this.SetAttributeValue("dpe_compareattributelogicalname", value);
				this.OnPropertyChanged("dpe_CompareAttributeLogicalName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_compareto")]
		public virtual dpe_policyconditioncompare? dpe_CompareTo
		{
			get
			{
				return ((dpe_policyconditioncompare?)(EntityOptionSetEnum.GetEnum(this, "dpe_compareto")));
			}
			set
			{
				this.OnPropertyChanging("dpe_CompareTo");
				this.SetAttributeValue("dpe_compareto", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dpe_CompareTo");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_comparetoname")]
		public string dpe_comparetoName
		{
			get
			{
				if (this.FormattedValues.Contains("dpe_compareto"))
				{
					return this.FormattedValues["dpe_compareto"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_name")]
		public string dpe_Name
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_name");
			}
			set
			{
				this.OnPropertyChanging("dpe_Name");
				this.SetAttributeValue("dpe_name", value);
				this.OnPropertyChanged("dpe_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_operator")]
		public virtual dpe_policyconditionoperator? dpe_Operator
		{
			get
			{
				return ((dpe_policyconditionoperator?)(EntityOptionSetEnum.GetEnum(this, "dpe_operator")));
			}
			set
			{
				this.OnPropertyChanging("dpe_Operator");
				this.SetAttributeValue("dpe_operator", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dpe_Operator");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_operatorname")]
		public string dpe_operatorName
		{
			get
			{
				if (this.FormattedValues.Contains("dpe_operator"))
				{
					return this.FormattedValues["dpe_operator"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_policyconditionid")]
		public System.Nullable<System.Guid> dpe_PolicyConditionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dpe_policyconditionid");
			}
			set
			{
				this.OnPropertyChanging("dpe_PolicyConditionId");
				this.SetAttributeValue("dpe_policyconditionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("dpe_PolicyConditionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_policyconditionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.dpe_PolicyConditionId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_policyruleid")]
		public Microsoft.Xrm.Sdk.EntityReference dpe_PolicyRuleId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dpe_policyruleid");
			}
			set
			{
				this.OnPropertyChanging("dpe_PolicyRuleId");
				this.SetAttributeValue("dpe_policyruleid", value);
				this.OnPropertyChanged("dpe_PolicyRuleId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_policyruleidname")]
		public string dpe_PolicyRuleIdName
		{
			get
			{
				if (this.FormattedValues.Contains("dpe_policyruleid"))
				{
					return this.FormattedValues["dpe_policyruleid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_sequence")]
		public System.Nullable<int> dpe_Sequence
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dpe_sequence");
			}
			set
			{
				this.OnPropertyChanging("dpe_Sequence");
				this.SetAttributeValue("dpe_sequence", value);
				this.OnPropertyChanged("dpe_Sequence");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valueboolean")]
		public System.Nullable<bool> dpe_ValueBoolean
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dpe_valueboolean");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueBoolean");
				this.SetAttributeValue("dpe_valueboolean", value);
				this.OnPropertyChanged("dpe_ValueBoolean");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuebooleanname")]
		public string dpe_valuebooleanName
		{
			get
			{
				if (this.FormattedValues.Contains("dpe_valueboolean"))
				{
					return this.FormattedValues["dpe_valueboolean"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuedatetime")]
		public System.Nullable<System.DateTime> dpe_ValueDateTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dpe_valuedatetime");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueDateTime");
				this.SetAttributeValue("dpe_valuedatetime", value);
				this.OnPropertyChanged("dpe_ValueDateTime");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuedecimal")]
		public System.Nullable<decimal> dpe_ValueDecimal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("dpe_valuedecimal");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueDecimal");
				this.SetAttributeValue("dpe_valuedecimal", value);
				this.OnPropertyChanged("dpe_ValueDecimal");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valueguid")]
		public string dpe_ValueGuid
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_valueguid");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueGuid");
				this.SetAttributeValue("dpe_valueguid", value);
				this.OnPropertyChanged("dpe_ValueGuid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuelookupid")]
		public string dpe_ValueLookupId
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_valuelookupid");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueLookupId");
				this.SetAttributeValue("dpe_valuelookupid", value);
				this.OnPropertyChanged("dpe_ValueLookupId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuelookuplogicalname")]
		public string dpe_ValueLookupLogicalName
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_valuelookuplogicalname");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueLookupLogicalName");
				this.SetAttributeValue("dpe_valuelookuplogicalname", value);
				this.OnPropertyChanged("dpe_ValueLookupLogicalName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuemoney")]
		public Microsoft.Xrm.Sdk.Money dpe_ValueMoney
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dpe_valuemoney");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueMoney");
				this.SetAttributeValue("dpe_valuemoney", value);
				this.OnPropertyChanged("dpe_ValueMoney");
			}
		}
		
		/// <summary>
		/// Value of the Value Money in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuemoney_base")]
		public Microsoft.Xrm.Sdk.Money dpe_valuemoney_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dpe_valuemoney_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valueoptionsetvalue")]
		public System.Nullable<int> dpe_ValueOptionSetValue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dpe_valueoptionsetvalue");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueOptionSetValue");
				this.SetAttributeValue("dpe_valueoptionsetvalue", value);
				this.OnPropertyChanged("dpe_ValueOptionSetValue");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuestring")]
		public string dpe_ValueString
		{
			get
			{
				return this.GetAttributeValue<string>("dpe_valuestring");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueString");
				this.SetAttributeValue("dpe_valuestring", value);
				this.OnPropertyChanged("dpe_ValueString");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuetype")]
		public virtual dpe_policyconditionvaluetype? dpe_ValueType
		{
			get
			{
				return ((dpe_policyconditionvaluetype?)(EntityOptionSetEnum.GetEnum(this, "dpe_valuetype")));
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueType");
				this.SetAttributeValue("dpe_valuetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dpe_ValueType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuetypename")]
		public string dpe_valuetypeName
		{
			get
			{
				if (this.FormattedValues.Contains("dpe_valuetype"))
				{
					return this.FormattedValues["dpe_valuetype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_valuewholenumber")]
		public System.Nullable<int> dpe_ValueWholeNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dpe_valuewholenumber");
			}
			set
			{
				this.OnPropertyChanging("dpe_ValueWholeNumber");
				this.SetAttributeValue("dpe_valuewholenumber", value);
				this.OnPropertyChanged("dpe_ValueWholeNumber");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Policy Condition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual dpe_policycondition_statecode? statecode
		{
			get
			{
				return ((dpe_policycondition_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Policy Condition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual dpe_policycondition_statuscode? statuscode
		{
			get
			{
				return ((dpe_policycondition_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 dpe_policycondition_PolicyRuleId_dpe_policyrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dpe_policyruleid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dpe_policycondition_PolicyRuleId_dpe_policyrule")]
		public DataversePolicyEnforcement.Models.dpe_PolicyRule dpe_policycondition_PolicyRuleId_dpe_policyrule
		{
			get
			{
				return this.GetRelatedEntity<DataversePolicyEnforcement.Models.dpe_PolicyRule>("dpe_policycondition_PolicyRuleId_dpe_policyrule", null);
			}
			set
			{
				this.OnPropertyChanging("dpe_policycondition_PolicyRuleId_dpe_policyrule");
				this.SetRelatedEntity<DataversePolicyEnforcement.Models.dpe_PolicyRule>("dpe_policycondition_PolicyRuleId_dpe_policyrule", null, value);
				this.OnPropertyChanged("dpe_policycondition_PolicyRuleId_dpe_policyrule");
			}
		}
	}
}
#pragma warning restore CS1591
