#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataversePolicyEnforcement.Models.OptionSets
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum dpe_policyconditionvaluetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WholeNumber = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Decimal = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Money = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DateTime = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionSet = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lookup = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guid = 8,
	}
}
#pragma warning restore CS1591
