#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataversePolicyEnforcement.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("dpe_GetAttributeDecisions")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class dpe_GetAttributeDecisionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string dpe_gad_entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_entitylogicalname"))
				{
					return ((string)(this.Parameters["dpe_gad_entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dpe_gad_entitylogicalname"] = value;
			}
		}
		
		public string[] dpe_gad_targetattributelogicalnames
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_targetattributelogicalnames"))
				{
					return ((string[])(this.Parameters["dpe_gad_targetattributelogicalnames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["dpe_gad_targetattributelogicalnames"] = value;
			}
		}
		
		public string dpe_gad_triggerattributelogicalname
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggerattributelogicalname"))
				{
					return ((string)(this.Parameters["dpe_gad_triggerattributelogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggerattributelogicalname"] = value;
			}
		}
		
		public int dpe_gad_triggercurrentvalue_int
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggercurrentvalue_int"))
				{
					return ((int)(this.Parameters["dpe_gad_triggercurrentvalue_int"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggercurrentvalue_int"] = value;
			}
		}
		
		public string dpe_gad_triggercurrentvalue_lookup_logicalname
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggercurrentvalue_lookup_logicalname"))
				{
					return ((string)(this.Parameters["dpe_gad_triggercurrentvalue_lookup_logicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggercurrentvalue_lookup_logicalname"] = value;
			}
		}
		
		public string dpe_gad_triggercurrentvalue_lookupid
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggercurrentvalue_lookupid"))
				{
					return ((string)(this.Parameters["dpe_gad_triggercurrentvalue_lookupid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggercurrentvalue_lookupid"] = value;
			}
		}
		
		public int dpe_gad_triggercurrentvalue_optionsetvalue
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggercurrentvalue_optionsetvalue"))
				{
					return ((int)(this.Parameters["dpe_gad_triggercurrentvalue_optionsetvalue"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggercurrentvalue_optionsetvalue"] = value;
			}
		}
		
		public string dpe_gad_triggercurrentvalue_string
		{
			get
			{
				if (this.Parameters.Contains("dpe_gad_triggercurrentvalue_string"))
				{
					return ((string)(this.Parameters["dpe_gad_triggercurrentvalue_string"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dpe_gad_triggercurrentvalue_string"] = value;
			}
		}
		
		public dpe_GetAttributeDecisionsRequest()
		{
			this.RequestName = "dpe_GetAttributeDecisions";
			this.dpe_gad_entitylogicalname = default(string);
			this.dpe_gad_targetattributelogicalnames = default(string[]);
			this.dpe_gad_triggerattributelogicalname = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("dpe_GetAttributeDecisions")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class dpe_GetAttributeDecisionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public dpe_GetAttributeDecisionsResponse()
		{
		}
		
		public string dpe_gad_attributedecision_results
		{
			get
			{
				if (this.Results.Contains("dpe_gad_attributedecision_results"))
				{
					return ((string)(this.Results["dpe_gad_attributedecision_results"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["dpe_gad_attributedecision_results"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
